import type { Metadata } from "next";
import "./globals.css";
import MyHeader from "../components/myLayout/MyHeader"
import { Playfair_Display, Lora, Poppins, Dancing_Script } from 'next/font/google';
import MyFooter from "@/components/myLayout/MyFooter";

const playfair = Playfair_Display({ subsets: ['latin'], weight: ['400', '700'], variable: '--font-playfair' });
const lora = Lora({ subsets: ['latin'], weight: ['400', '700'], variable: '--font-lora' });
const poppins = Poppins({ subsets: ['latin'], weight: ['400', '500', '700'], variable: '--font-poppins' });
const dancingScript = Dancing_Script({ subsets: ['latin'], weight: ['400', '700'], variable: '--font-dancing' });


export const metadata: Metadata = {
  title: "Anousha's Food Blog",
  description: "Generated by Anousha Asadullah",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
     className={`${playfair.variable} ${lora.variable} ${poppins.variable} ${dancingScript.variable} antialiased`}
      >
         <MyHeader />
         <div>{children}</div>
         <MyFooter/>
      </body>
    </html>
  );
}
